%YAML:1.0
---
calibration_time: "2019年4月06日 星期六"
nframes: 35
image_width: 640
image_height: 480
square_size: 35

#640x480 由RGB2XYZ中计算而来
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [5333.310033210447, 0, 2816.514523830436,
          0.,5333.349632254521, 1408.804956809039,
          0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [-0.346029396127828,0.118312006703833,0.000278020655464680,-0.00121469675043767,0.0216094331403231]

#Extrinsic parameters init 以相机坐标系为参考坐标系
offset_x: 10
offset_y: 100
offset_z: 10
angle_x: 3
angle_y: -90     #再绕动y’_camera轴转-90
angle_z: 90      #先绕z_camera轴转90度

#Iteration
step_offset: 10  #mm
step_angle: 1    #degree
max_hit_rate: 0.98
max_iter_number: 3

#CameraSet
width : 640
height : 480

#Process
dataset_number: 5
gray_threshold: 155
pointcloud_threshold: 200

#Debug
debug_show_image: 0
debug_show_pointcloud: 0
debug_show_coordinate: 1
debug_process: 0
debug_calculate: 0


