%YAML:1.0
---
calibration_time: "2019年4月06日 星期六"

#CameraSet
width: 8256
height: 5504 

#640x480 由RGB2XYZ中计算而来
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [3247.04833412716, 0, 4168.21265002673,
          0.,3257.37311000803, 2774.24637745092,
          0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [-0.0125891489513001,-0.00940350679819408,0.00218134412958731,5.83576873999360e-05,0.00378618213644217]

#Extrinsic parameters init 以相机坐标系为参考坐标系
offset_x: 0       #单位mm
offset_y: 120
offset_z: 0
angle_x: 0        #pitch
angle_y: -90      #yaw  再绕动y’_camera轴转-90度
angle_z: 90       #roll 先绕z_camera轴转90度

#Up and down
y_up: 150
y_dowm: 90
z_up: 50
z_down: -50
angelY_up: -70
angleY_down: -1110

#Iteration
dataset_number: 1
step_offset: 10  #mm
step_angle: 3    #degree
max_hit_rate: 0.8
max_iter_number: 2   #实际迭代+1次

#Debug
debug_show_image: 0
debug_show_pointcloud: 0
debug_show_coordinate: 0
debug_process: 0
debug_calculate: 0


